import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "90%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ecf0f1",
    position: "relative",
    marginLeft: 15,
    borderWidth: 1,
    marginTop: 10,
    borderRadius: 5,
    marginBottom: 18,
  },
  header: {
    flexDirection: "row",
    marginTop: 35,
    justifyContent: "space-around",
    alignItems: "center",
  },
  textHeader: {
    marginTop: 10,
    textAlign: "center",
    justifyContent: "center",
    fontSize: 26,
  },
  button: {
    width: 80,
    height: 80,
    borderRadius: 25,
    backgroundColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  button2: {
    width: 80,
    height: 80,
    borderRadius: 25,
    backgroundColor: "#ddd",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    marginLeft: 150,
  },
  horizontalButtons: {
    flexDirection: "row",
    gap: 60,
    marginLeft: 75,
  },
  conteinerButton: {
    height: "90%",
    width: "90%",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ecf0f1",
    position: "relative",
    marginLeft: 15,
    borderWidth: 1,
    marginTop: 60,
    borderRadius: 5,
    marginBottom: 18,
  },
  textStart: {
    textAlign: "center",
    justifyContent: "center",
    fontSize: 26,
    color: "#fff",
  },
  buttomStart: {
    width: 200,
    height: 100,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "blue",
    backgroundColor: "blue",
    marginTop: 500,
  },
  backgroundImage: {
    alignItems: "center",
    justifyContent: "center",
    resizeMode: "cover",
    width: "100%",
    height: "100%",
    maxWidth: 350, // Ajuste o valor conforme necessário
    maxHeight: 300, // Ajuste o valor conforme necessário
  },
});
